name: Node.js

on:
  schedule:
    - cron: '0 21 * * 0-4'

jobs:
  run:
    #    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Run
        run: |
          for try in {1..10}; do
            xvfb-run npm start && break
            sleep 30
          done
        env:
          CHROMIUM_HEADFUL: 1
          MICROSOFT_EMAIL: ${{ secrets.MICROSOFT_EMAIL }}
          MICROSOFT_PASSWORD: ${{ secrets.MICROSOFT_PASSWORD }}
